var GameData = [
  {
    name: "The Witcher 3: Wild Hunt",
    sourceUrl:
      "https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/",
    description:
      "As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world.",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    releaseDate: "18 May 2015",
    tags: [
      "Open World",
      "RPG",
      "Story Rich",
      "Atmospheric",
      "Mature",
      "Fantasy",
      "Adventure",
      "Singleplayer",
      "Choices Matter",
      "Nudity",
      "Great Soundtrack",
      "Third Person",
      "Action",
      "Medieval",
      "Multiple Endings",
      "Action RPG",
      "Magic",
      "Dark Fantasy",
      "Dark",
      "Sandbox",
    ],
    tags_short: ["RPG", "Dark Fantasy", "Story Rich"],
    game_sources: ["Steam", "Gog", "Epic Games"],
    slug: "the_witcher",
  },
  {
    name: "Kingdom Come: Deliverance",
    sourceUrl:
      "https://store.steampowered.com/app/379430/Kingdom_Come_Deliverance/",
    description:
      "Story-driven open-world RPG that immerses you in an epic adventure in the Holy Roman Empire. Avenge your parents' death as you battle invading forces, go on game-changing quests, and make influential choices. Explore castles, forests, villages and other realistic settings in medieval Bohemia!",
    developer: "Warhorse Studios",
    publisher: "Warhorse Studios",
    releaseDate: "13 Feb 2018",
    tags_short: ["Medieval", "Realistic", "Choose Your Own Adventure"],
    tags: [
      "Medieval",
      "RPG",
      "Open World",
      "Realistic",
      "Singleplayer",
      "Historical",
      "Adventure",
      "First-Person",
      "Story Rich",
      "Swordplay",
      "Action",
      "Nudity",
      "Choices Matter",
      "Choose Your Own Adventure",
      "Atmospheric",
      "Horses",
      "Great Soundtrack",
      "Indie",
      "Kickstarter",
      "Crowdfunded",
    ],
    slug: "kingdom_come",
  },
  {
    name: "Destroy All Humans!",
    sourceUrl: "https://store.steampowered.com/app/803330/Destroy_All_Humans/",
    description:
      "The cult-classic returns! Terrorize the people of 1950's Earth in the role of the evil alien Crypto-137. Harvest their DNA and bring down the US government in the faithful remake of the legendary alien invasion action adventure. Annihilate puny humans using an assortment of alien weaponry and psychic abilities.",
    developer: "Black Forest Games",
    publisher: "THQ Nordic",
    releaseDate: "28 Jul, 2020",
    tags_short: ["Villain Protagonist", "Aliens", "Dark Humor"],
    tags: [
      "Action",
      "Adventure",
      "Villain Protagonist",
      "Aliens",
      "Remake",
      "Open World",
      "Singleplayer",
      "Funny",
      "Sci-fi",
      "Cult Classic",
      "Comedy",
      "Gore",
      "Third Person",
      "Destruction",
      "Third-Person Shooter",
      "Dark Humor",
      "Classic",
      "Sandbox",
      "Violent",
      "Multiplayer",
    ],
    slug: "destroy_all",
  },
  {
    name: "Slay the Spire",
    sourceUrl: "https://store.steampowered.com/app/646570/Slay_the_Spire/",
    description:
      "We fused card games and roguelikes together to make the best single player deckbuilder we could. Craft a unique deck, encounter bizarre creatures, discover relics of immense power, and Slay the Spire!",
    developer: "Mega Crit Games",
    publisher: "Mega Crit Games",
    releaseDate: "23 Jan, 2019",
    tags_short: ["Roguelike", "Deckbuilding", "Procedural Generation"],
    tags: [
      "Roguelike Deckbuilder",
      "Card Game",
      "Card Battler",
      "Roguelike",
      "Deckbuilding",
      "Turn-Based",
      "Strategy",
      "Singleplayer",
      "Roguelite",
      "Replay Value",
      "Indie",
      "Difficult",
      "Dungeon Crawler",
      "RPG",
      "Mouse only",
      "Great Soundtrack",
      "2D",
      "Fantasy",
      "Procedural Generation",
      "Casual",
    ],
    slug: "slay_spire",
  },
  {
    name: "Mount & Blade II: Bannerlord",
    sourceUrl:
      "https://store.steampowered.com/app/261550/Mount__Blade_II_Bannerlord/",
    description:
      "The horns sound, the ravens gather. An empire is torn by civil war. Beyond its borders, new kingdoms rise. Gird on your sword, don your armour, summon your followers and ride forth to win glory on the battlefields of Calradia. Establish your hegemony and create a new world out of the ashes of the old.",
    developer: "TaleWorlds Entertainment",
    publisher: "TaleWorlds Entertainment",
    releaseDate: "30 Mar, 2020",
    tags_short: ["Medieval", "War", "Sandbox"],
    tags: [
      "Medieval",
      "Strategy",
      "Open World",
      "RPG",
      "War",
      "Multiplayer",
      "Sandbox",
      "Singleplayer",
      "Action",
      "Simulation",
      "Character Customization",
      "Moddable",
      "Adventure",
      "Horses",
      "Realistic",
      "Third Person",
      "First-Person",
      "Historical",
      "Great Soundtrack",
      "Early Access",
    ],
    slug: "bannerlord",
  },
  {
    name: "Evil Genius 2: World Domination",
    sourceUrl:
      "https://store.steampowered.com/app/700600/Evil_Genius_2_World_Domination/",
    description:
      "A satirical spy-fi lair builder where YOU are the criminal mastermind! Construct your base, train your minions, defend your operations from the Forces of Justice, and achieve global domination!",
    developer: "Rebellion",
    publisher: "Rebellion",
    releaseDate: "30 Mar, 2021",
    tags_short: ["Villain Protagonist", "Base Building", "Resource Management"],
    tags: [
      "Strategy",
      "Simulation",
      "Base Building",
      "Villain Protagonist",
      "Building",
      "Management",
      "Singleplayer",
      "Violent",
      "Sandbox",
      "Memes",
      "Funny",
      "Resource Management",
      "Sequel",
      "RTS",
      "Cartoony",
      "Great Soundtrack",
      "Co-op",
      "Sexual Content",
      "Comedy",
      "Multiplayer",
    ],
    slug: "evil_genius",
  },
  {
    name: "Grounded",
    sourceUrl: "https://store.steampowered.com/app/962130/Grounded/",
    description:
      "The world is a vast, beautiful and dangerous place – especially when you have been shrunk to the size of an ant. Can you thrive alongside the hordes of giant insects, fighting to survive the perils of the backyard?",
    developer: "Obsidian Entertainment",
    publisher: "Xbox Game Studios",
    releaseDate: "28 Jul, 2020",
    tags_short: ["Survival", "Base Building", "Crafting"],
    tags: [
      "Survival",
      "Multiplayer",
      "Base Building",
      "Crafting",
      "Co-op",
      "Adventure",
      "Open World Survival Craft",
      "Open World",
      "Action",
      "Horror",
      "Online Co-Op",
      "Exploration",
      "Early Access",
      "First-Person",
      "Sandbox",
      "Singleplayer",
      "RPG",
      "Third Person",
      "Funny",
      "Cute",
    ],
    slug: "grounded",
  },
  {
    name: "Age of Empires IV",
    sourceUrl: "https://store.steampowered.com/app/1466860/Age_of_Empires_IV/",
    description:
      "One of the most beloved real-time strategy games returns to glory with Age of Empires IV, putting you at the center of epic historical battles that shaped the world.",
    developer: "Relic Entertainment",
    publisher: "Xbox Game Studios",
    releaseDate: "28 Oct, 2021",
    tags_short: ["Medieval", "RTS", "Resource Management"],
    tags: [
      "Strategy",
      "RTS",
      "Multiplayer",
      "Medieval",
      "Singleplayer",
      "Historical",
      "War",
      "Resource Management",
      "Action RTS",
      "Base Building",
      "PvP",
      "PvE",
      "City Builder",
      "3D",
      "Isometric",
      "Co-op",
      "Sexual Content",
      "Open World",
      "Management",
      "Online Co-Op",
    ],
    slug: "age_empires",
  },
  {
    name: "Borderlands 2",
    sourceUrl: "https://store.steampowered.com/app/49520/Borderlands_2/",
    description:
      "The Ultimate Vault Hunter’s Upgrade lets you get the most out of the Borderlands 2 experience.",
    developer: "Gearbox Software",
    publisher: "2K",
    releaseDate: "21 Sep, 2012",
    tags_short: ["Shooter", "Loot", "Open World"],
    tags: [
      "Loot",
      "Shooter",
      "Action",
      "Multiplayer",
      "Co-op",
      "Looter Shooter",
      "FPS",
      "RPG",
      "First-Person",
      "Funny",
      "Comedy",
      "Open World",
      "Combat",
      "Online Co-Op",
      "Adventure",
      "Action RPG",
      "Dark Humor",
      "Memes",
      "Singleplayer",
      "Sci-fi",
    ],
    slug: "borderlands",
  },
  {
    name: "LongestExampleLongestExampleLongestExampleLongestExampleLongestExampleLongestExampleLongestExample!",
    sourceUrl:
      "LongestExampleLongestExampleLongestExampleLongestExampleLongestExampleLongestExampleLongestExample!",
    description:
      "DescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMaxDescriptionMa",
    developer:
      "developermaxdevelopermaxdevelopermaxdevelopermaxdevelopermaximu",
    publisher:
      "publishermaxpublishermaxpublishermaxpublishermaxpublishermaximu",
    releaseDate: "20 Feb 2022",
    tags: [
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
    ],
    tags_short: [
      "maxlengthmaxlengthmaxlengthmaxlengthmaxlengthmaxl",
      "MAXLENGTHMAXLENGTHMAXLENGTHMAXLENGTHMAXLENGTHMAXL",
      "MaximusLengtholusMaximusLengtholusMaximusLengthol",
    ],
    slug: "LongestExampleLongestExampleLongestExampleLongestExampleLongestExampleLongestExampleLongestExamplee",
  },
  {
    name: "Mini",
    sourceUrl: "https://bleepbloop.minim.web",
    description: "A minimal description.",
    developer: "MiMo",
    publisher: "Momo",
    releaseDate: "01 Jan, 1980",
    tags: ["Mupp"],
    tags_short: ["Mupp"],
    slug: "mi",
  },
];

export { GameData };
